# Generated by Django 2.2 on 2019-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190501_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_text',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(
                default='dummy content', max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
